# Generated by Django 2.1.7 on 2019-02-16 15:35
import secrets

from django.db import migrations, models
from blog.models import make_random_password


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_course_unique_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(default=make_random_password, max_length=50),
        ),
    ]
