# Generated by Django 2.1.7 on 2019-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190406_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived_box',
            field=models.BooleanField(default=False),
        ),
    ]
