# Generated by Django 2.1.7 on 2019-12-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_course_archived_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='archived_box',
            new_name='archived',
        ),
    ]
