# Generated by Django 4.1.1 on 2022-09-14 11:42

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_course_naucse_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="naucse_slug",
            field=blog.models.NaucseSlugField(
                blank=True,
                help_text="Pokud je vyplněno, kurz bude propojen s daným kurzem na naucse.",
                max_length=500,
                null=True,
            ),
        ),
    ]
